name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Cache ~/.elm
        uses: actions/cache@v2
        with:
          path: ~/.elm
          key: elm

      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Flow
        run: npx --no-install flow check

      - name: ESLint
        run: npx --no-install eslint --report-unused-disable-directives .

      - name: Prettier
        run: npx --no-install prettier --check .

      - name: elm-format
        run: npx --no-install elm-format --validate elm

      - name: elm-review
        run: npx --no-install elm-review
        working-directory: elm
